#6 Поменял все ссылки на url_for()
md5orsha256/flask-hello-app pull request #12
Opened 2021-03-25 08:47 UTC by iasman312

2021-03-25 09:24 UTC, md5orsha256 commented
у вас там конфликт, нужно обновить ваш форк

2021-03-26 08:17 UTC, iasman312 commented
Обновил)

2021-03-28 17:30 UTC, md5orsha256 requested changes

2021-03-31 05:23 UTC, md5orsha256 approved these changes

2021-03-31 05:23 UTC, merged